/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/app": `/app`,
  "/app/categorias": `/app/categorias`,
  "/app/categorias/criar_editar": `/app/categorias/criar_editar`,
  "/app/fornecedores": `/app/fornecedores`,
  "/app/fornecedores/criar_editar": `/app/fornecedores/criar_editar`,
  "/app/permissoes_telas": `/app/permissoes_telas`,
  "/app/permissoes_telas/editar/[tela]": (params: { tela: (string | number) }) => {
    return `/app/permissoes_telas/editar/${params['tela']}`
  },
  "/app/produtos": `/app/produtos`,
  "/app/produtos/criar_editar": `/app/produtos/criar_editar`,
  "/app/telas": `/app/telas`,
  "/app/telas/criar_editar": `/app/telas/criar_editar`,
  "/app/usuarios": `/app/usuarios`,
  "/app/usuarios/criar_editar": `/app/usuarios/criar_editar`,
  "/login": `/login`
}

/**
 * SERVERS
 */
const SERVERS = {
  
}

/**
 * ACTIONS
 */
const ACTIONS = {
  "logout /app": `/app?/logout`,
  "salvar /app/permissoes_telas/editar/[tela]": (params: { tela: (string | number) }) => {
    return `/app/permissoes_telas/editar/${params['tela']}?/salvar`
  },
  "save /app/usuarios/criar_editar": `/app/usuarios/criar_editar?/save`,
  "default /login": `/login`
}

/**
 * LINKS
 */
const LINKS = {
  
}

type ParamValue = string | number | boolean | null | undefined

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?',
) => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  let anchor = ''
  for (const [name, val] of Object.entries(sp)) {
    if (name === '__KIT_ROUTES_ANCHOR__' && val !== undefined) {
      anchor = `#${val}`
      continue
    }
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted || anchor) {
    return `${prefix}${formatted}${anchor}`.replace('?#', '#')
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

/* type helpers for route function */
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

export type Routes = keyof AllTypes extends `${string}/${infer Route}` ? `/${Route}` : keyof AllTypes
export const routes = [
	...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[]

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/app': never, '/app/categorias': never, '/app/categorias/criar_editar': never, '/app/fornecedores': never, '/app/fornecedores/criar_editar': never, '/app/permissoes_telas': never, '/app/permissoes_telas/editar/[tela]': 'tela', '/app/produtos': never, '/app/produtos/criar_editar': never, '/app/telas': never, '/app/telas/criar_editar': never, '/app/usuarios': never, '/app/usuarios/criar_editar': never, '/login': never }
  SERVERS: Record<string, never>
  ACTIONS: { 'logout /app': never, 'salvar /app/permissoes_telas/editar/[tela]': 'tela', 'save /app/usuarios/criar_editar': never, 'default /login': never }
  LINKS: Record<string, never>
  Params: { 'tela': never }
}
